### ISSUE TITLE
Not working with laravel and webpack

### ISSUE THREAD

**Issue by dientuki** [kraaden/autocomplete#1]
Hi, just that. I'm tring to use in a Laravel 5.3 project and it's dons't work. It's use webpack to compile the js

**Comment by denis-taran** [comment]
Hi dientuki,

I updated the NPM package and fixed an issue with webpack, so you should be able to use this package  now.

Please install the latest version:

    npm install autocompleter@1.0.16

then import it in javascript:

    import autocomplete from 'autocompleter';
    // or
    var autocomplete = require('autocompleter');
