### ISSUE TITLE
iOS candidate word selection does not trigger autocomplete

### ISSUE THREAD

**Issue by jivdhaliwal** [kraaden/autocomplete#100]
Tested on iPhone 14 (using Simulator)
Browser: Safari
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1

While testing the library on iOS I found that the autocomplete was not fetching results when a candidate word suggestion was selected. For example an auto-correct suggestion when a typo is made, or when typing using a phonetic input method (e.g. Zhuyin) and selecting candidate words.

I've attached a video of this behaviour, with event monitoring enabled and logging added to the fetch method on the demo site:

https://user-images.githubusercontent.com/7527178/215103424-279de837-8415-4ae2-88f5-f19e7b7b2aea.mp4

As we can see in the example, when the auto-correct suggestion is selected ("Luxembourg"), a textInput text event is triggered with the candidate word. As there are no keyup events sent, the autocomplete library is not fetching. 

Only after subsequent keyup events does the auto complete trigger.

In cases where someone is using an input method that requires selection of candidate words like Zhuyin, this results in the autocompleter fetching based on the last keyup event before the final word was selected.

For example when someone searches for Egg 蛋, they type "ㄉㄢˋ" and then select the correct candidate word. But they will see autocomplete results for "ㄉㄢˋ" until they submit another keyup event (like pressing space).

Thanks for your work on the library 🙏

**Comment by jivdhaliwal** [comment]
Related issues: 
https://github.com/kraaden/autocomplete/issues/78 due to keyup events not firing in certain circumstances
https://github.com/kraaden/autocomplete/issues/91 due to keyup events firing on keyup events for keys that do not change the input

**Comment by denis-taran** [comment]
This issue should be fixed in the last version:

    npm install autocompleter@8.0.0-alpha.1

**Comment by jivdhaliwal** [comment]
Thanks for the fast response, greatly appreciated 🙌
