### ISSUE TITLE
Container width is always set as the input width causing UI problems

### ISSUE THREAD

**Issue by ghiscoding** [kraaden/autocomplete#102]
#### Description of the problem
I'm using this lib in an open source datagrid and I render the autocomplete data that can be wider than the autocomplete input. However in the current code implementation, the autocomplete container can never be wider than the input because it is set by the library and the data end up overflowing and is not very usable as shown in the image below, it is also not easy to override because it is set directly on the input width style.

https://github.com/kraaden/autocomplete/blob/360619d94b9fd5f65554a195f66e9a8cb97e826f/autocomplete.ts#L243-L245

#### Proposal
A proposal could be to assign the `width` only via an option, something like `autoDropWidth: true` that could be defined as `true` by default, if however set to `false` then the lib shouldn't be assigning the width at all.

### Reproduction
You can replicate this issue by going in my open source data grid here: 
https://ghiscoding.github.io/slickgrid-universal/#/example12

### Current Solution (very hacky)
The only solution that I found for now, which is very hacky, is to unset the width via `!important` on the autocomplete width property.

```css
.autocomplete {
  width: unset !important;
}
```
--- 

#### current behavior with `width` being assigned input width
![image](https://user-images.githubusercontent.com/643976/217700574-6f9b3b02-a590-4d02-a4b5-21fda9d610f7.png)

#### without the lib assigning `width` 
![image](https://user-images.githubusercontent.com/643976/217698693-30d89627-45c1-451c-b964-e622d20ce60e.png)

**Comment by denis-taran** [comment]
Hi, you can set an arbitrary width, height and other properties for your container in the `customize` function:

    autocomplete({
        ...,
        customize: function(input, inputRect, container, maxHeight) {
            container.style.width = '500px';
            container.style.height = '200px';
        }
    });

**Comment by ghiscoding** [comment]
ok I see, it seems to also work by assigning an empty string to unset the width  like this
```js
customize: (_input, _inputRect, container) => {
    container.style.width = '';
},
```
However, I would still prefer to not have to set it at all (via a flag) but if you really don't want to add a flag then I can work with that. Feel free to close the issue if you think the `customize` is the way to go and you don't want to add any flag

Thanks for the great lib
