### ISSUE TITLE
emptyMsg Shows on Resize When Using Custom Container

### ISSUE THREAD

**Issue by bcrotty** [kraaden/autocomplete#103]
Similar to #3, the emptyMsg shows when I resize the browser window if I specify my own container in the autocomplete settings. If I let it use the default generated container, the message does not appear on resize.

**Comment by denis-taran** [comment]
Hi @bcrotty 

Could you please provide a minimal reproducible example? I just tested autocomplete with a custom container and both suggestions and empty message are properly attached to my custom DOM container (both initially or while resizing).

**Comment by bcrotty** [comment]
Sorry for the delay. Here you go:

```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kraaden.github.io/autocomplete/autocomplete.js"></script>
  </head>
  <body>
    <div id="search-container">
      <input type="text" id="search" />
      <div id="search-results"></div>
    </div>
    <script>
      const input = document.getElementById("search");

      document.addEventListener("DOMContentLoaded", () => {
        autocomplete({
          input,
          emptyMsg: "No results found",
          container: document.getElementById("search-results"),
        });
      });
    </script>
  </body>
</html>
```

When I resize my browser when viewing that page, the `emptyMsg` text appears. Disabling the `container` parameter fixes the issue.

**Comment by denis-taran** [comment]
@bcrotty I fixed the issue in the latest version
