### ISSUE TITLE
Slow navigation with arrow up/down keys due to redraw of autocomplete div

### ISSUE THREAD

**Issue by lionelduriez** [kraaden/autocomplete#106]
Hi,

I am using autocomplete with lists containing around 300 hundred suggestions when fetch is triggered with minLength=1.
On one screen, the list contains more than 2000 suggestions.

When using the mouse wheel to scroll through the suggestions, no performance issue is noticed and scrolling is fast and smooth: update() is not called when scrolling through the suggestions with the mouse wheel.

When using keyboard keys ArrowUp or ArrowDown to navigate the suggestions, we notice a slowness induced by function update() which is called each time keys ArrowUp or ArrowDown are pressed: each arrow key up/down press triggers the redraw of the autocomplete div element with suggestions.

Here are somes logs gathered in Chrome DevTools console when performance issue occurs:

Whith 327 suggestions: 
> [Violation] Forced reflow while executing JavaScript took 34ms
[Violation] Forced reflow while executing JavaScript took 36ms
[Violation] Forced reflow while executing JavaScript took 35ms
[Violation] Forced reflow while executing JavaScript took 37ms
[Violation] Forced reflow while executing JavaScript took 39ms

With 2272 suggestions:
> [Violation] 'keydown' handler took 191ms
[Violation] 'keydown' handler took 217ms
[Violation] 'keydown' handler took 188ms
[Violation] 'keydown' handler took 217ms
[Violation] 'keydown' handler took 188ms
[Violation] Forced reflow while executing JavaScript took 139ms
[Violation] Forced reflow while executing JavaScript took 137ms
[Violation] Forced reflow while executing JavaScript took 134ms
[Violation] Forced reflow while executing JavaScript took 135ms
[Violation] Forced reflow while executing JavaScript took 136ms

I have developped a fix which consists in updating the selected suggestion after each ArrowUp or ArrowDown key press without redrawing the autocomplete div element.
I will link a pull request to the issue.

Thanks for this great widget !

**Comment by lionelduriez** [comment]
Same slow navigation with arrow keys reported in this issue: https://github.com/kraaden/autocomplete/issues/47

**Comment by lionelduriez** [comment]
Pull request: #107

**Comment by denis-taran** [comment]
Hi @lionelduriez Thank you very much for the contribution! You can now install new version with your changes by using the following command:

    npm install autocompleter@9.0.0-alpha.0

**Comment by lionelduriez** [comment]
Hello @kraaden ! Thanks for the great support and alpha release !
I just switched to 9.0.0-alpha.0 in dev.
