### ISSUE TITLE
exports missing autocomplete.css

### ISSUE THREAD

**Issue by grahamlangford** [kraaden/autocomplete#113]
Is it possible to get the `autocomplete.css` added to the `exports` field in the package.json? 

I'm running into `Module not found: Error: Package path ./autocomplete.css is not exported from package` when building with webpack.

**Comment by denis-taran** [comment]
@grahamlangford I added `autocomplete.css` to the export in `package.json` file. Let me know if the issue is fixed now.

**Comment by grahamlangford** [comment]
That fixed it! Thanks for the quick turnaround!
