### ISSUE TITLE
Existing container CSS classes are lost

### ISSUE THREAD

**Issue by matthew-darby** [kraaden/autocomplete#116]
When using the `container` parameter, any existing CSS classes on the container are lost.

I understand there is the `className` parameter, but it would be nice to not have to declare them here.

https://jsbin.com/bimehemuxe/1/edit?html,js,output

**Before:**

`<div class="containerClass1 containerClass2" id="container"></div>`

**After:**

`<div class="autocomplete " id="container"></div>`

**Comment by denis-taran** [comment]
Hi Matthew, thank you for reporting this issue. It should be fixed in the new version 9.3.0
