### ISSUE TITLE
module has no exported member autocomplete

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [kraaden/autocomplete#13]
Since last version i'm getting this error when and can't initialize the autocomplete as it says that it's not a function. basic reproduction below

https://stackblitz.com/edit/angular-autocompleter-13

**Comment by denis-taran** [comment]
Just replace

    import { autocomplete, AutocompleteSettings, AutocompleteItem, AutocompleteResult } from "autocompleter";

with

    import autocomplete, { AutocompleteSettings, AutocompleteItem, AutocompleteResult } from "autocompleter";

and then it should work.

**Comment by tiagomsmagalhaes** [comment]
Thanks. Why does it have to be outside brackets and the others inside? Tried to look for other examples but couldn't find an explanations

**Comment by denis-taran** [comment]
This is because all interfaces are declared as named exports, but `autocomplete` is default export in the package.

I would acually prefer to add named export for `autocomplete` too, but if I do this, `rollup` will modify `UMD` header and replace global declaration for `autocomplete` with `autocomplete.autocomplete`.

Currently `UMD` header looks like this:

    (function (global, factory) {
      typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
      typeof define === 'function' && define.amd ? define(factory) :
      (global.autocomplete = factory());
    }(this, (function () { 'use strict';
    ...

and if I change function declaration to `export function autocomplete...`, then the generated `UMD` header will look like this:

    (function (global, factory) {
      typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
      typeof define === 'function' && define.amd ? define(['exports'], factory) :
      (factory((global.autocomplete = {}))); // must be called as autocomplete.autocomplete(...)
    }(this, (function (exports) { 'use strict';

**Comment by planger** [comment]
When importing `autocomplete` as below, I still get a `TypeError: c.default is not a function`.
```typescript
import autocomplete, { AutocompleteSettings, AutocompleteItem, AutocompleteResult } from "autocompleter";
```

The only way of importing autocomplete that works for me is:
```typescript
const configureAutocomplete: (settings: AutocompleteSettings<YourItemType>) => AutocompleteResult = require("autocompleter");
```

Could this be related to Babel? See also https://github.com/Microsoft/TypeScript/issues/5565

Thanks a lot!

**Comment by denis-taran** [comment]
@planger This is exactly how it should work. I tried to reproduce this issue, but I can compile it with both babel and typescript without any issues:

https://github.com/kraaden/autocomplete-tst/tree/master/my-app

**Comment by planger** [comment]
> @planger This is exactly how it should work. I tried to reproduce this issue, but I can compile it with both babel and typescript without any issues:
> 
> https://github.com/kraaden/autocomplete-tst/tree/master/my-app

Thanks a lot for the fast reply, @kraaden!

Good that it works in the test project. I'm not sure why it doesn't work in our project though. I guess there seems to be a difference in the transpiler config... hm. Thanks anyways!
