### ISSUE TITLE
Bug with scrollEventHandler() call prevents autocomplete container from scrolling

### ISSUE THREAD

**Issue by corford** [kraaden/autocomplete#14]
I ran in to an issue today and tracked it down to (I think!) the way scrollEventHandler is being fired.

**Issue:**
With `overflow: auto` set for the `.autocomplete` container and the first item in the list automatically selected/highlighted when autocomplete first opens with suggestions (as per default behavior), you cannot then use the mouse to scroll the container's scrollbar to browse other items. `updateScroll()` prevents this due to this piece of code:

`
 if (element.offsetTop < container.scrollTop) {
  container.scrollTop = element.offsetTop;
}
`

To reproduce the issue, simply resize the browser window so the autocomplete container doesn't have enough vertical space to display all of its child items/suggestions (and thus overflows with a scroll bar). If the first suggestion is selected, scrolling down with the mouse will not work. If you use the keyboard up/down buttons to move through the list, you will find scrolling will work again until the newly selected/highlighted suggestion reaches the top or bottom of the container.

**Why is this happening?**
I think it may be because of how the scroll event is being bound:
`doc.addEventListener("scroll", scrollEventHandler, true);`

Passing `true` (i.e. putting it in capture mode) causes `scrollEventHandler()` to fire first and intercept the scroll action of the autocomplete container. This then in turn triggers a full rebuild of the autocomplete container, ending in a call to `updateScroll()` which blocks the scroll.

Maybe a fix would be to turn off capture mode for the main scroll event listener (i.e. pass `false` as last arg) and also prevent scroll events from the autocomplete container from bubbling up?

Alternatively, maybe scrollEventHandler() can inspect the call site of the event and, if it originated from the autocomplete container element, simply discard it rather than triggering an update.

**Comment by corford** [comment]
I've just tried taking the scroll event out of capture mode (on a test build of your js source) and it fixed the issue BUT... this then means the autocomplete container doesn't track the input element position on scroll (in my case the input element is sitting in a modal window which has its own scroll bar, not the main document scrollbar).

So I guess the cleanest fix would be to maintain capture mode for document scroll but then discard the event/noop if it was originated from the autocomplete container itself?

**Comment by denis-taran** [comment]
Hi Charlie, could you please check the branch `scrollfix` and tell me if it fixed the issue?

**Comment by corford** [comment]
That was quick 👍 Works perfectly!

**Comment by denis-taran** [comment]
Thanks! The update is now available on NPM
