### ISSUE TITLE
Bug with ignored keys causing fetch callback to skip update()

### ISSUE THREAD

**Issue by corford** [kraaden/autocomplete#16]
Hi again (sorry for bugging you so much lately)!

I bumped in to a bug tonight with the way autocomplete handles ignored keys in the `keyup()` func.

The problem is the position of this line: `var savedKeypressCounter = ++keypressCounter;`

`savedKeypressCounter` and `keypressCounter` get incremented before the ignored keys and down key checks are performed. If `keyup()` returns early as a result of one of these checks being positive, the callback function passed to `fetch` reads an earlier value of `savedKeypressCounter` causing the `if (keypressCounter === savedKeypressCounter && elements)` check to fail (since `savedKeypressCounter` is local to the `keyup()` func and its earlier value is no longer in sync with the current value of `keypressCounter`, which is a global var).

To see this bug in action, you simply need to enter some text in the input field while holding down the SHIFT key (e.g. imagine the input field was for entering airport three letter codes, some people like to enter these in upper case and use SHIFT to do it rather than caps lock). In this case `fetch` fires but no results are shown as `update()` is never called by the callback function.

**The fix** seems easy: simply move the line that increments `saveKeypressCounter` and `keypressCounter` BELOW the ignored keys and down key checks. Basically, place `var savedKeypressCounter = ++keypressCounter;` directly after:

`          if (keyCode === 40 /* Down */ && containerDisplayed()) {
              return;
          }
`

**Comment by denis-taran** [comment]
It is fixed now in `3.0.3`

**Comment by corford** [comment]
Thanks!
