### ISSUE TITLE
min-height and height interfere with the scrolling under Chrome

### ISSUE THREAD

**Issue by ghost** [kraaden/autocomplete#17]
The `min-height` and `height` attributes are causing autocomplete pop-up background to be not correctly sized under both mobile and desktop Chrome, so whenever user scrolls the page, the items at the bottom of the list would appear without a background.

In my case the solution was to remove [autocomplete.ts:138](https://github.com/kraaden/autocomplete/blob/a74107a68cac42489ba06dcb8ada506dd809ec02/autocomplete.ts#L138) and [autocomplete.ts:139](https://github.com/kraaden/autocomplete/blob/a74107a68cac42489ba06dcb8ada506dd809ec02/autocomplete.ts#L139).

**Comment by denis-taran** [comment]
Removing 138 and 139 will make the autocomplete unscrollable and it will always be displayed in full height, no matter if there are enough space for it below.
