### ISSUE TITLE
Viewport boundary bugs with updatePosition()

### ISSUE THREAD

**Issue by corford** [kraaden/autocomplete#18]
There are two container height bugs caused by this line in the `updatePosition()` function:
`
containerStyle.maxHeight = (window.innerHeight - top) + "px";
`

**Bug 1:**
`top` accounts for scrollTop but `window.innerHeight` does not. This means if the input element autocomplete is attached to is below the fold of the page, `maxHeight` is never set by the browser as the value is negative. Note: I'm not sure if this is a true bug or intentional behaviour.

**Bug 2 (more important):**
If the input element that autocomplete is attached to happens to be right on the lower edge of the viewport, maxHeight is set and ends up clipping the suggestions container to a tiny px value (e.g. 1 or 2 px high).

We discovered the above issues when a user with an unusual screen resolution (1920x1200) complained that the suggestions were not displaying correctly. It turns out that because of Bug 1 above, we had not noticed anything strange on our 1920x10180 monitors (because the input was off screen and maxHeight never got applied). On his screen the input was right at the lower edge of the viewport and so suggestions were being clipped to a height of 2px.

**The fix is easy:**
Get the height of the container and correctly account for scrollTop.

Revised `updatePosition()` could look something like this:

```javascript
        function updatePosition() {
            if (!containerDisplayed()) {
                return;
            }
            containerStyle.height = "auto";
            containerStyle.width = input.offsetWidth + "px";
            var docEl = doc.documentElement;
            var clientTop = docEl.clientTop || doc.body.clientTop || 0;
            var clientLeft = docEl.clientLeft || doc.body.clientLeft || 0;
            var scrollTop = window.pageYOffset || docEl.scrollTop;
            var scrollLeft = window.pageXOffset || docEl.scrollLeft;
            function calc() {
                var inputRect = input.getBoundingClientRect();
                var top = inputRect.top + input.offsetHeight + scrollTop - clientTop;
                var left = inputRect.left + scrollLeft - clientLeft;
                var height = container.getBoundingClientRect().height;
                containerStyle.top = top + "px";
                containerStyle.left = left + "px";
                if ((((scrollTop + window.innerHeight) - (top + height)) < 1) && (clipHeight > 0)) {
                     // clip container to height needed to keep it in viewport (but make sure clipped height is no less than `clipHeight`)
                    var difference = (top + height) - (scrollTop + window.innerHeight);
                    containerStyle.maxHeight = ((height - difference) > clipHeight) ? height - difference + 'px' : clipHeight + 'px';
                }
            }
            // we need to recalculate layout twice, because sometimes it will return an invalid value for inputRect.left on the first call
            calc();
            calc();
        }
```

And then add:
`var clipHeight = settings.clipHeight || 0;` to `autocomplete()` function (which preserves the previous behaviour but gives users the option to apply a minimum maxHeight on containers that spill out below the viewport).

**Comment by corford** [comment]
I've implemented the above fixes (plus added an unrelated `selectOnTab` option) on my fork here: https://github.com/corford/autocomplete

**Comment by denis-taran** [comment]
Hi Charlie, thank you for reporting this issue. Could you please check new branch for autocomplete? I added a new option that allows to display autocomplete above when there is not enough space below. It works a bit differently and will not increase height for HTML body element.

**Comment by denis-taran** [comment]
In the new version `4.0.0-alpha.2` you can display autocomplete above the input field by setting `customize` callback.

**Comment by corford** [comment]
Sorry @kraaden I've been snowed under with work and didn't get a chance to test this. I see you've pushed it out now so will check it out sometime soon.
