### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by corford** [kraaden/autocomplete#19]
Hi.

Because of this line in the `keyup` function:

```javascript
if (keypressCounter === savedKeypressCounter && elements) {
```

If `elements` is an empty array (which evaluates to true in javascript), the `update()` function is called. If `elements` is false (i.e. developer chooses to ignore the current documentation and passes false as parameter to the fetch callback), `update()` is not called.

This is actually quite nice as it gives the developer a choice of what to do in the situation where e.g. they are using ajax to power the autocomplete suggestions and a user types the beginning of a place name, ajax returns with some results and user keeps on typing. In this case, if another ajax request is fired but this time no results come back, the developer can decide whether to pass an empty array in the fetch calback (thus closing the suggestions) or pass `false` (which would keep the suggestions open from the first ajax result).

I am using the above technique at the moment and it is actually quite useful. Maybe the documentation for `fetch` should mention this possibility so others can benefit?

**Comment by corford** [comment]
Also, another doc suggestion! :)

```javscript
var countries = [
    { label: 'United Kingdom', value: 'UK', group: "North America" },
    { label: 'United States', value: 'US', group: "North America" },
    { label: 'Uzbekistan', value: 'UZ', group: "Asia" },
];
```

UK is not in North America. Maybe Canada makes more sense...

```javascript
var countries = [
    { label: 'Canada', value: 'CA', group: "North America" },
    { label: 'United States', value: 'US', group: "North America" },
    { label: 'Uzbekistan', value: 'UZ', group: "Asia" },
];
```

**Comment by denis-taran** [comment]
Thank you for the suggestions, Charlie. I updated the docs.
