### ISSUE TITLE
textarea

### ISSUE THREAD

**Issue by neuropass** [kraaden/autocomplete#2]
Hi,would this work inside a textarea? 
for example to be used to call users mention github style with the @username 

Let me know your thoughts.

**Comment by denis-taran** [comment]
Hi Neuropass,

It is only possible to select a single value with this widget.

You probably need something like multiselect:
https://jedwatson.github.io/react-select/

**Comment by denis-taran** [comment]
You can try to use it with textareas, but it is not officially supported and there may be some problems when you use the ENTER key.
