### ISSUE TITLE
show all suggestions on focus

### ISSUE THREAD

**Issue by alizadeh118** [kraaden/autocomplete#20]
Hi

I want to show all suggestions when the input is focused. without further input by the user.

Is there already a way to trigger `autocomplete` manually or any option to set like setting `minLength: 0`?

Thank you.

**Comment by denis-taran** [comment]
There is no way to do this at the moment without modifying the widget, because it doesn't listen for `focus` event.

**Comment by codewinkel** [comment]
Is it on your roadmap for future implementations?

**Comment by denis-taran** [comment]
Not at the moment, because it's not a frequently asked feature

**Comment by losbeekos** [comment]
I'd like to see this feature implemented too, it's way better UX IMO.

**Comment by shaikemarc** [comment]
Makes sense just for local suggestions but not for api based

**Comment by denis-taran** [comment]
It is now possible to show suggestions on focus event. Just install the version `5.0.0-alpha.2` and add the following option to your configuration:

    {
        ...
        showOnFocus: true
    }
