### ISSUE TITLE
Resize will show "AutocompleteSettings.emptyMsg"

### ISSUE THREAD

**Issue by Chrico** [kraaden/autocomplete#3]
When resizing the window (e.G. switching from landscape into portrait mode) the autocomplete will trigger the [`update`](https://github.com/kraaden/autocomplete/blob/master/autocomplete.ts#L338) function.

This is ok so far, because maybe you would have to re-calculate the position if the search input has different styles. But if you have nothing entered yet, so the autocomplete-list is not visible, it will show the list with `AutocompleteSettings.emptyMsg`.

You can reproduce this when going to https://kraaden.github.io/autocomplete/ and just grab the window and resize it. The message will appear, even you've never started to type anything before.

The "easiest" way would be to introduce a new function which behaves like following:

```ts
function updateOnResize(): boolean {
    if(!containerDisplayed()){
        return false;
    }
    update();
    return true;
}
```

Additionally you've to update `window.removeEventListener("resize", updateOnResize);` and `window.addEventListener("resize", updateOnResize);` according to the new function.

**Comment by denis-taran** [comment]
Hi Chrico,

Thank you very much for reporting this issue.

I updated GitHub/Npm package and the problem should be fixed now.

**Comment by Chrico** [comment]
Perfect! Thanks a lot. 👍
