### ISSUE TITLE
Form is submitting on enter (selection)

### ISSUE THREAD

**Issue by victorbueno** [kraaden/autocomplete#32]
When pressing the enter key to select, the form is being submitted.

The only way I can select an item is using the mouse. How can I select on enter?

Also, would be nice to select on "tab". Eg.: use arrow keys to select and press tab.

**Comment by denis-taran** [comment]
You can now prevent automatic submit using the latest version and the following option:

```javascript
autocomplete({
    ...,
    preventSubmit: true
});
```

**Comment by victorbueno** [comment]
@kraaden Thank you very much!
