### ISSUE TITLE
Autocomplete closing when dismissing keyboard in IOS

### ISSUE THREAD

**Issue by akaver** [kraaden/autocomplete#34]
When you close keyboard in iOS with done, autocomplete also closes (focus out event?). Would like to have an option keep autocomplete still open, to scroll around in long list of choices - without keyboard taking up half the screen.

**Comment by denis-taran** [comment]
Unlike Android, IOS will fire blur/focus events even when the keyboard is closing. As far as I know there is no easy way to determine if the blur event was fired by closing keyboard or something else.

**Comment by denis-taran** [comment]
There is probably nothing I can do, so I gonna close the issue.
