### ISSUE TITLE
Option to Disable Select Item on Enter

### ISSUE THREAD

**Issue by spikecodes** [kraaden/autocomplete#37]
Hi, I'm trying to allow users to press enter to search the text inside their input but because of the code block below, it get's triggered by another `addEventListener` registering the item as selected:

```js
if (keyCode === 13 /* Enter */) {
 if (selected) {
     settings.onSelect(selected, input);
     clear();
 }
 if (preventSubmit) {
     ev.preventDefault();
 }
}
```
It would be great if you could add a config option to disable this Select on Enter functionality from happening.

Cheers,
Spike

**Comment by cdalexndr** [comment]
Search engines (Google, Bing, DuckDuckGo) autocomplete doesn't automatically select the first item on Enter.
This is a **required feature** that users are used to.

**Comment by denis-taran** [comment]
You can just extend the default functionality with typescript:

```ts
interface ExtendedSettings<T> extends AutocompleteSettings<T> {
    disableAutoSelect: boolean;
}

function autocompleteCustomized<T extends AutocompleteItem>(settings: ExtendedSettings<T>): AutocompleteResult {
    return autocomplete({
        ...settings,
        onSelect(item: T, input: HTMLInputElement) {
            if (settings.disableAutoSelect) {
                return;
            }
            settings.onSelect(item, input);
        }
    });
}
```

Then call it like this:

```ts
autocompleteCustomized({
    disableAutoSelect: true,
    ...
})
```

**Comment by cdalexndr** [comment]
@kraaden with this code manual select will not work, rendering autocomplete unusable. `onSelect` is called when user presses Enter or when he clicks an entry in the dropdown. If the user selects an entry with the arrow keys (onSelect not called) and presses enter (onSelect called), the selection will be ignored, but he clearly wants that entry to be applied.

What is needed is an option to prevent autoselect **only** if the user doesn't want to apply a suggestion and wants to submit raw input text. 
How can you detect the user doesn't want the autocomplete applied? One example: if he doesn't press "down" and selects an entry, then he doesn't want to autocomplete. This requires that by default no entry is selected, as opposed to current behavior where the first entry is selected on initialization and an entry must **always** be selected.

Can you please review my PR https://github.com/kraaden/autocomplete/pull/40?

**Comment by hoebelix** [comment]
Any progress on this? I completely agree with @cdalexndr.

**Comment by cdalexndr** [comment]
I'm currently using my fork with the feature enabled, until PR is approved: 
`npm install --save github:cdalexndr/autocomplete#disableAutoSelect_issue37`

**Comment by josipmaslac** [comment]
@cdalexndr thanks for that, hope @kraaden will approve PR soon.

I need a behaviour that would prevent submit by default (ignoring `preventSubmit` setting) if an Enter is pressed while an item selected (which to me should be a common use case).
So I've got that by taking a code from PR #40 and changing the part from the first post in this thread by introducing a new setting `preventSubmitOnSelect`:

```javascript
if (keyCode === 13 /* Enter */) {
    if (selected) {
        if (settings.preventSubmitOnSelect === true){
            ev.preventDefault();
        }
        settings.onSelect(selected, input);
        clear();
    } 
    if (preventSubmit) {
        ev.preventDefault();
    }
}
```

@kraaden if this addition makes sense to you please add it also.
