### ISSUE TITLE
After updating autocomplete, it stopped working

### ISSUE THREAD

**Issue by trondeh80** [kraaden/autocomplete#38]
I updated the npm dependency to the latest version (5.1.3), and the plugin stopped working.
When I am debugging autocomplete.js I see that this expression always evaluates to false: `keypressCounter === savedKeypressCounter` in the "startFetch" function.

This is how we are setting up our autocomplete:
```
const input = document.getElementById('product');
	const products = getProducts();
	if (products.length && !!input) {
		autocomplete({
			input: input,
			fetch: (text, update) => {
				text = text.toLowerCase();
				const suggestions = products.filter(n => n.label.toLowerCase().startsWith(text));
				update(suggestions);
			},
			onSelect: ({ label }) => {
				input.value = label;
			},
			minLength: 1,
			emptyMsg: 'No matches'
		});
	}
```
What are we doing wrong?

This was tested on mac os v10.13.6 on a chrome Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by denis-taran** [comment]
I copied your code here:

https://jsbin.com/kasezelaza/edit?html,js,output

and everything seems to work just fine. If I enter 'u' into the input field, it shows suggestions correctly (tested with the same browser & version)

**Comment by trondeh80** [comment]
Ok, sounds like we had a bug on our end then. Your component was rendered as part of a material component in our form. We decided to use a drop-down instead for now. Thank you very much for looking in to this, and for creating this awesome plugin.
