### ISSUE TITLE
The bug is related to incorrect calculation of css properties top.

### ISSUE THREAD

**Issue by cvaize** [kraaden/autocomplete#41]
Device: Apple iPhone 5 32Gb MD295LL/A
Browser Safari, user agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_4 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G61 Safari/602.1

The bug is related to incorrect calculation of css properties top. At the same time, if you change css position c fixed to absolute, then autocomplete will appear in the right place.

![image](https://user-images.githubusercontent.com/26907947/70977676-3607f900-20d0-11ea-9730-3debc63f67ed.png)

![image](https://user-images.githubusercontent.com/26907947/70977300-731fbb80-20cf-11ea-9900-601acdca56c4.png)

**Comment by cvaize** [comment]
If you remove this code, everything works, what fixes this code?
![image](https://user-images.githubusercontent.com/26907947/70988544-e0d5e280-20e3-11ea-9718-17523e559a2b.png)

**Comment by cvaize** [comment]
@kraaden

**Comment by cvaize** [comment]
#33 Here this problem was raised, for what this fix ? He clearly becomes the cause of the bug.

**Comment by denis-taran** [comment]
The issue should be fixed in the latest version
