### ISSUE TITLE
Is it possible to disallow values not in list ?

### ISSUE THREAD

**Issue by MROALI** [kraaden/autocomplete#44]
In my use case i want only that user choose value from the list.  and dissalow him for entering another value or text. Other saying, i want only to text to be only fill using on select event.

**Comment by denis-taran** [comment]
@MROALI 

Please check the following branch (last commit):
https://github.com/kraaden/autocomplete/tree/inputrestriction

Is this something you are looking for?

**Comment by MROALI** [comment]
Thankyou i tested it but not working. I don't know what i did wrong. 

I can no more select value from the list. It's always keeping the initial value loaded in the input.

When i put a breakpoint in the select function it works, otherwise not working. Do you have any idea ?

This is my code : 
`autocomplete({
              minLength: 1,
              input: address,
              debounceWaitMs:200,
              preventSubmit: true,
              inputRestriction : 2,
              minLength: 5,
              fetch: function(query, update) {
                  query = query.toLowerCase();
                  $.ajax({
                      url: urlAPI + query,
                        type: "get",
                        crossDomain: true,
                        dataType: 'json',
                        success: function(data) {
                            var processedData = _instance.getAddressFromJson(data);
                            update(processedData);
                        }
                   });

              },
              onSelect: function(item, input) {
            	  var addressValue = item.name;
                  if(postCode.length) {
                	  postCode.val(item.postCode);
                	  postCode.blur();
                  }
                  
                  if(city.length) {
                	  city.val(item.city);
                	  city.blur();
                  }
                  
                  if(postCode.length == 0 && city.length == 0) {
                	  addressValue = item.label;
                  }
                  
                  $(input).val(addressValue);
                  $(input).blur();
              }
          });`

**Comment by denis-taran** [comment]
You should delay the `$(input).blur()` call with `setTimeout` in `onSelect`, otherwise it will immedeately update the input field.

[JS BIN](https://jsbin.com/nanowosizi/1/edit?html,js,output)

**Comment by thomasphilibert** [comment]
Nice and simple feature kraaden, thank you.

**Comment by thomasphilibert** [comment]
Hi Krraaden,

Your solution work fine but, if you type partialy and dont select any value of list, the input get previous value:
 
![Enregistrement de l’écran 2020-03-13 à 00 54 26](https://user-images.githubusercontent.com/4984828/76577492-e1ed9480-64c5-11ea-8b72-a1fe81949003.gif)

Best,
Thomas
