### ISSUE TITLE
Do search in my word

### ISSUE THREAD

**Issue by tosipaulo** [kraaden/autocomplete#5]
Please, how can I do a search in the middle of the word? ex: label is United Kingdom and enter only 'ing' and Sorry for English ;)

**Comment by denis-taran** [comment]
If all your data is in memory, you can use the following:

    var countries = [
        { label: 'United Kingdom', item: 'UK' },
        { label: 'United States', item: 'US' }
    ];
    
    autocomplete({
        input: document.getElementById("country"),
        fetch: function(text, update) {
            text = text.toLowerCase();
            var suggestions = countries.filter(n => n.label.toLowerCase().indexOf(text) !== -1)
            update(suggestions);
        },
        onSelect: function(item) {
            alert(item);
        }
    });

then it will seach in the whole text, not just beginning.
