### ISSUE TITLE
Allow any text and click select another cell

### ISSUE THREAD

**Issue by mikkovor** [kraaden/autocomplete#54]
Hi,

Ag-Grid seems to be a pretty bad way to enter new data to the grid. I am trying to implement a way for a user to either select an option from the autocomplete and that will automatically fill the rest of the pinned row columns with that specific items other values. Now there should also be an option for creating a completely new item so it would go like this: User types a name and maybe clicks the next row. How can I actually 'save' this free text now? Also Tab triggers both onFreeTextSelect AND onSelect, i guess there is a way to around this problem. Enter would select the free text / selection but enter also creates a new row from the data in the pinned row so that's a problem as well.

**Comment by denis-taran** [comment]
Hi,

This is a wrong repository for the issue and it should be opened here:

https://github.com/ag-grid/ag-grid/issues
