### ISSUE TITLE
Interface for show\hide autocomplete panel 

### ISSUE THREAD

**Issue by ashemetov** [kraaden/autocomplete#57]
There is a need to show\hide autocomplete panel outside of it - for instance, there maybe history button that will autocomplete panel.
Maybe two more functions can be added, something like:
```
function show() {
    startFetch(1);
}
function hide() {
    clear();
 }
...
return {
    destroy: destroy,
    show: show,
    hide: hide,
};
```

**Comment by rajniszp** [comment]
+1, would be very useful
