### ISSUE TITLE
Tag new versions

### ISSUE THREAD

**Issue by ashemetov** [kraaden/autocomplete#58]
Will really appreciate if new version will be tagged in git with version number.
In some cases (like FF extensions) link onto exact code is needed (see [How to determine the third-party library link](https://extensionworkshop.com/documentation/publish/third-party-library-usage/)), tags will help to provide a link onto exact version.

**Comment by Taitava** [comment]
I'd like to have tags, too! 🙂

**Comment by Taitava** [comment]
Hi @kraaden ! 🙂 Would it be possible to have tags for new versions? It would make it easier for me to see which commits are included in an npm release (and which commits are not yet released). 👍 

Edit: If Releases were used (in addition to tagging), it would also allow me to get notifications on GitHub when a new version is available. 🌞
