### ISSUE TITLE
Not working in strict mode due to body.scrollTop

### ISSUE THREAD

**Issue by MisterAJ** [kraaden/autocomplete#6]
Since body.scrollTop doesn't work in strict mode. The autocomplete shows up in the wrong place.

**Comment by MisterAJ** [comment]
PR https://github.com/kraaden/autocomplete/pull/7 to fix

**Comment by denis-taran** [comment]
@MisterAJ I've updated the npm package with the fix and I also fixed another issue related to window scrolling.

**Comment by MisterAJ** [comment]
Thanks :-)
