### ISSUE TITLE
Limit displayed results

### ISSUE THREAD

**Issue by srahmi** [kraaden/autocomplete#66]
Is there a way to limit the results displayed by the component?

**Comment by josipmaslac** [comment]
Yes, you can do that in the `fetch` method by limiting the number of suggestions that you pass to the callback function manually.

For example:

```javascript
fetch: function(searchText, callback) {
    var suggestions = customFetchCode(searchText); // your code that returns an array of suggested items
    callback(suggestions.slice(0,10));  // show only first 10 suggestions
}
```
