### ISSUE TITLE
Allow HTML in label

### ISSUE THREAD

**Issue by pontikis** [kraaden/autocomplete#68]
Hello, thanks for this great plugin!

Is there a way to use HTML in "label"? Thanks

![ksnip_20201218-230118](https://user-images.githubusercontent.com/814012/102661249-2577dc00-4185-11eb-8705-2044874c5e3c.png)

**Comment by denis-taran** [comment]
Yes, you can use `render` function for that:

    render: function(item, value) {
        ...
        var element = document.createElement("div");
        element.innerHTML = "your html";
        return element;
    }

**Comment by pontikis** [comment]
Thank you!

**Comment by pontikis** [comment]
Yes, it works! Thanks again.

![ksnip_20201219-000416](https://user-images.githubusercontent.com/814012/102665707-f74aca00-418d-11eb-8eab-5f852fd07af9.png)
