### ISSUE TITLE
Autocomplete with new value

### ISSUE THREAD

**Issue by sushib** [kraaden/autocomplete#69]
Hi,

I am looking for autocomplete that allow new value?

Cheers

**Comment by denis-taran** [comment]
You can generate new values in the `fetch` method:

    autocomplete({
        input: document.getElementById("textfieldid"),
        fetch: function(text, update) {
            text = text.toLowerCase();
            var suggestions = [];
            for (var i = 0; i < 10; i++) {
              var item = text + "_" + Math.round(Math.random() * 10000).toString();
              suggestions.push({
                label: item,
                value: item
              });
            }
            update(suggestions);
        },
        onSelect: function(item) {
            input.value = item.label;
        }
    });
