### ISSUE TITLE
Add accessibility attributes to support screen readers

### ISSUE THREAD

**Issue by ofrias** [kraaden/autocomplete#71]
You can easily support screen readers just by adding a few HTML attributes:  https://accessibility.huit.harvard.edu/technique-aria-autocomplete

**Comment by ofrias** [comment]
This suggestion is still applicable, please don't close...

**Comment by denis-taran** [comment]
You can now install the latest version that supports accessibility attributes:

    npm i autocompleter@7.0.0-alpha.0
