### ISSUE TITLE
Auto complete is not working correctly on a jquery dialog box

### ISSUE THREAD

**Issue by inaraparaju** [kraaden/autocomplete#73]
I have tried adding it to a jquery dialog. But the suggestions box is not showing up at all. When I debug it...I can see that the div is added to the input by "updatePosition". But it is still not showing up. Do you have an example of this case?

**Comment by denis-taran** [comment]
No, I didn't test the widget with jQuery dialog, but you can try to increase `z-index` value in the css class `.autocomplete`. By default it is set to 1000.
