### ISSUE TITLE
Allow closing the list by pressing Esc

### ISSUE THREAD

**Issue by Taitava** [kraaden/autocomplete#81]
Hi,

is there a way to easily close the list of suggestions? I know the following ways to close it:
- Pressing Enter to select an item.
- Type more so that there will be no matching suggestions.

Thank you for your support! 🙂

**Comment by denis-taran** [comment]
You can already close the widget by pressing ESC key. You can visit the page below, open autocomplete and after pressing ESC it will be closed.

https://kraaden.github.io/autocomplete/

**Comment by Taitava** [comment]
Yea, it's true. I just noticed this a while ago from the source code. I had issues in my project when some other event listener interfered with detecting the esc key press. So this is all ok, thank you for your answer. 🙂👍
