### ISSUE TITLE
[Feature Request] Access object properties in onSelect Function

### ISSUE THREAD

**Issue by MisterAJ** [kraaden/autocomplete#9]
My data object has extra properties such as `id` and `value` that I would like to add to the input when the onSelect fires. 

I think adding this would help with many use cases.

**Comment by denis-taran** [comment]
In the new version you can access all properties directly:

    npm i --save-dev autocompleter@2.0.2

**Comment by MisterAJ** [comment]
You're the best! I very much appreciate your effort :-)
