### ISSUE TITLE
fetch called after autocomplete selection on Firefox Android

### ISSUE THREAD

**Issue by ofrias** [kraaden/autocomplete#99]
On Firefox Mobile, the `fetch` function is called immediately after selecting one of the autocomplete options.

This is caused by this code:

```
var mobileFirefox = ~userAgent.indexOf("Firefox") && ~userAgent.indexOf("Mobile");
[...]
// 'keyup' event will not be fired on Mobile Firefox, so we have to use 'input' event instead
var keyUpEventName = mobileFirefox ? "input" : "keyup";

```
As of January 2023, the current Firefox for Android (version 108.2.0) does support the `keyup` event, so this custom browser sniffing code should be removed.

Thanks!

**Comment by denis-taran** [comment]
Thanks! I removed the code and published an updated version on npm.
